### ISSUE TITLE
Upsert node won't show up. Other nodes work perfectly.

### ISSUE THREAD

**Issue by ajayjohn** [serene-water/node-red-contrib-coda-io#4]
I am a huge fan of Node-Red and only recently discovered Coda. I was thrilled to see that you have created a package for Coda, opening up numerous possibilities for the platform!

I tried installing the package and was able to successfully fetch table entities, rows etc. However, I cannot get the upsert node to show up. No matter what I do, it initially shows up in enabled state (but will show no entry in the sidebar). Once I disable it and try to enable it again, it will never get enabled. Could you help me here, please?

**Comment by sorjef** [comment]
Same issue for me. Node-red version v1.0.3 deployed with docker

**Comment by dokumori** [comment]
Thanks for the report and apologies for the silence. I fixed the issue based on the [patch davecahill submitted](https://github.com/serene-water/node-red-contrib-coda-io/pull/5). The problem was caused by a variable being defined twice. The release v0.6.6 includes the fix.

I haven't tested the package thoroughly so while the upsert node now loads, I am not 100% certain if all the nodes remain fully compatible with the latest version of Coda.
